version: '3.7'
services:
  mysql:
    image: bitnami/mysql:latest
    hostname: db
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
      MYSQL_ROOT_PASSWORD: 'lepYSeG4QoSe'
    ports:
      - 3306:3306
    networks:
      - REDE1
  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_HOST: db
      MAX_EXECUTION_TIME: 300
      MEMORY_LIMIT: 256M
      UPLOAD_LIMIT: 64M
    ports:
      - 8080:80
    networks:
      - REDE1
  redis:
    image: redis:latest
    volumes:
      - data-redis:/data
    ports:
      - 6379:6379
    networks:
      - REDE1
volumes:
  data-storage:
    external: true
    name: data-storage
  data-tmp:
    external: true
    name: data-tmp
  data-mysql:
    external: true
    name: data-mysql
  data-redis:
    external: true
    name: data-redis
  
networks:
  REDE1:
    external: true
    name: REDE1
